#%RAML 1.0 NamedExample
localization:
  timestamp: Sun, 28 Feb 2016 16:41:41 GMT
  techs:
   -
    id: 1
    value: "Metal Mine"
   -
    id: 2
    value: "Crystal Mine"
  missions:
   -
    id: 1
    value: "Attack"
   -
    id: 2
    value: "ACS Attack"