#%RAML 1.0 NamedExample
server:
  timestamp: Sun, 28 Feb 2016 16:41:41 GMT
  serverId: "ar101"
  name: "Andromeda"
  number: 101
  language: "ar"
  timezone: "America/Buenos_Aires"
  timezoneOffset: "-03:00"
  domain: "s101-ar.ogame.gameforge.com"
  version: "6.7.0-pl3"
  speed: 1
  speedFleet: 1
  galaxies: 9
  systems: 499
  acs: true
  rapidFire: true
  defToTF: false
  debrisFactor: 0.3
  debrisFactorDef: 0
  repairFactor: 0.7
  newbieProtectionLimit: 50000
  newbieProtectionHigh: 10000
  topScore: 76558727
  bonusFields: 25
  donutGalaxy: true
  donutSystem: true
  wfEnabled: true
  wfMinimumRessLost: 150000
  wfMinimumLossPercentage: 5
  wfBasicPercentageRepairable: 45
  globalDeuteriumSaveFactor: 1
  bashLimit: false
  probeCargo: false