#%RAML 1.0 DataType
type: object
properties:
  code:
    description: Unique error code
    type: string
    required: true
  message:
    description: Error message
    type: string
    required: true
  description:
    description: Error Description
    type: string
    required: false
