#%RAML 1.0 DataType
type: object
properties: 
  id: 
    type: integer
    minimum: 1
    description: Universe Unique Identifier
    example: 101
  href:
    type: string
    description: Universe URL
    example: https://s101-ar.ogame.gameforge.com
  name:
    type: string
    default: Universe Name
    example: Andromeda