#%RAML 1.0 NamedExample
universes:
  timestamp: Sun, 28 Feb 2016 16:41:41 GMT
  universes: 
      -
        id: 101
        href: "https://s101-ar.ogame.gameforge.com"
        name: "Andromeda"
      -
        id: 118
        href: "https://s118-ar.ogame.gameforge.com"
        name: "Rigel"