#%RAML 1.0 DataType
type: object
properties: 
  timestamp: !include ../utils/timestamp.raml
  alliances: 
    type: array
    items: !include alliance.raml
    description: Alliance Information
    example:
     -
        id: 500000
        name: German Warriors
        tag: "G-W"
        founder: 301015
        foundDate: Sun, 28 Feb 2016 16:41:41 GMT
        homepage: "http://homepage-url.com"
        logo: "http://logo-url.com"
        open: true
        player:
         -
          id: 301015
     -
        id: 500004
        name: Spanish Warriors
        tag: "S-W"
        founder: 511215
        foundDate: Sun, 28 Feb 2016 16:41:41 GMT
        homepage: "http://homepage-url.com"
        logo: "http://logo-url.com"
        open: true
        player:
         -
          id: 301015
         -
          id: 301017
         -
          id: 301018


  

