#%RAML 1.0 NamedExample
playerData:
  timestamp: Sun, 28 Feb 2016 16:41:41 GMT
  positions: 
      -
        type: "Total"
        score: 91369715
        position: 1
      -
        type: "Economy"
        score: 65401381
        position: 1
      -
        type: "Research"
        score: 11285970
        position: 1
      -
        type: Military
        score: 15845097
        position: 25
        ships: 749082
      -
        type: "Military Built"
        score: 11285970
        position: 1
      -
        type: "Military Destroyed"
        score: 11285970
        position: 1
      -
        type: "Military Lost"
        score: 11285970
        position: 1
      -
        type: "Honor"
        score: 11285970
        position: 1
  planets:
      -
        id: 33622803
        player: 302624
        name: "Homeworld"
        coords: "2:26:8"
      -
        id: 33622803
        player: 302624
        name: "Homeworld"
        coords: "2:26:8"
        moon:
          id: 33969999
          name: "Moon"
          size: 3741
  alliance:
      id: 500087
      name: "JusT KnucK N FutZ"
      tag: "Knuck"