#%RAML 1.0 NamedExample
players:
  timestamp: Sun, 28 Feb 2016 16:41:41 GMT
  players: 
      -
        id: 100003
        name: "comagf"
        status: "a"
        alliance: "500167"
      -
        id: 100004
        name: "OGameTeam"
        status: "a"